### ISSUE TITLE
不能获取cookies

### ISSUE THREAD

**Issue by ziyic** [kayanouriko/quantumultx-mihoyobbs-auto-helper#3]
按照README配置好后打开米游社app不显示获取cookies相关的通知，也没有成功获取

**Comment by kayanouriko** [comment]
重写打开了吗? 米游社登陆账号了吗?

**Comment by ziyic** [comment]
开了，也登录了……（有需要的话可以加个好友我给你发录屏）

**Comment by kayanouriko** [comment]
github 支持发视频的, 不方便处理视频发我邮箱吧 kayanouriko@icloud.com
